name: CI-CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # --------------------- Linting ---------------------
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Lint
        working-directory: ./backend
        run: npm run lint || true

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Lint
        working-directory: ./frontend
        run: npm run lint || true

      # --------------------- Tests ---------------------
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test || echo "No backend tests found"

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test || echo "No frontend tests found"

      # --------------------- Buildx ---------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --------------------- Docker Login ---------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --------------------- Build & Push Backend Image ---------------------
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: pk771/idurar-backend:latest

      # --------------------- Build & Push Frontend Image ---------------------
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: pk771/idurar-frontend:latest
